<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Coder.Desktop.App</RootNamespace>
    <AssemblyName>Coder Desktop</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <LangVersion>preview</LangVersion>
    <!-- AVP1002: DependencyObjectSelector intentionally registers generic AvaloniaProperty owners. -->
    <NoWarn>$(NoWarn);AVP1002</NoWarn>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.3" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.3" />
    <PackageReference Include="Svg.Skia" Version="2.0.0.6" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.3" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.2.3" Condition="'$(Configuration)' == 'Debug'" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.9" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\App.Linux\App.Linux.csproj" />
    <ProjectReference Include="..\Vpn.Linux\Vpn.Linux.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\App.Shared\App.Shared.csproj" Aliases="global,AppShared" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\\**" />
  </ItemGroup>
</Project>
